In [1]:
import numpy as np

In [2]:
array_1d = np.array([1,2,3,4,5])

In [4]:
print(array_1d)

[1 2 3 4 5]


In [5]:
print(type(array_1d))

<class 'numpy.ndarray'>


In [7]:
print(array_1d.ndim)

1


In [14]:
array_2d = np.array([[1,2,3,4],[5,6,7,8]])

In [17]:
print(array_2d)

[[1 2 3 4]
 [5 6 7 8]]


In [18]:
print(array_2d.size)

8


In [19]:
print(array_2d.size)

8


In [20]:
print(array_2d.shape)

(2, 4)


In [21]:
print(array_2d.dtype)

int64


In [26]:
matrix_array = np.array([[1,1,1,1],[1,1,1,1],[1,1,1,1]])

In [28]:
print(matrix_array)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [31]:
print(np.ones(5))

[1. 1. 1. 1. 1.]


In [32]:
print(np.dtype)

<class 'numpy.dtype'>


In [33]:
print(matrix_array.dtype)

int64


In [36]:
matrix1 = np.ones((1,5))

In [37]:
print(matrix1)

[[1. 1. 1. 1. 1.]]


In [39]:
matrix_1 = np.ones((3,5),dtype=int)

In [40]:
print(matrix_1)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


# arange()

In [41]:
oned_array = np.arange(1,15)

In [42]:
print(oned_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [44]:
even_array  = np.arange(1,15,2)

In [45]:
print(even_array)

[ 1  3  5  7  9 11 13]


# linespace

In [46]:
line = np.linspace(1,3,5)

In [47]:
print(line)

[1.  1.5 2.  2.5 3. ]


# reshape()

In [50]:
re_shape = array_2d.reshape(2,4)

In [52]:
print(re_shape)

[[1 2 3 4]
 [5 6 7 8]]


In [53]:
array_2d = np.arange(1,15).reshape(2,7)

In [54]:
print(array_2d)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


# ravel() convert multi to oned

In [55]:
print(array_2d.ravel())

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


# flatten()

In [56]:
print(array_2d.flatten())

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


# transpose matrix

In [57]:
print(array_2d.T)

[[ 1  8]
 [ 2  9]
 [ 3 10]
 [ 4 11]
 [ 5 12]
 [ 6 13]
 [ 7 14]]


# Mathmatics operation by using Numpy

In [58]:
array1 = np.arange(1, 10).reshape(3,3)

In [59]:
array2 = np.arange(1,10).reshape(3,3)

In [60]:
print(array1 + array2 )

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [62]:
print(np.add(array1,array2))

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [63]:
print(np.subtract(array1, array2))

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [64]:
print(np.divide(array1, array2))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [66]:
max_value1 = array1.dot(array2)

In [67]:
print(max_value1)

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [68]:
print(max_value1.max())

150


In [70]:
print(max_value1.max(axis=0))

[102 126 150]


In [71]:
print(max_value1.max(axis=1))

[ 42  96 150]


In [72]:
print(np.sum(max_value1))

729


In [73]:
print(np.min(max_value1))

30


In [74]:
print(np.mean(max_value1))

81.0


In [75]:
print(np.mean(max_value1, axis=0))

[66. 81. 96.]


In [76]:
print(np.mean(max_value1,axis=0,dtype=int))

[66 81 96]
